const c=document.getElementById("canvas"),ctx=c.getContext("2d"),$=id=>document.getElementById(id);
const GRID=50,HIVE=15;let W,H,COLS,rows=[],bee,score=0,level=1,runHoney=0,combo=0,best=+localStorage.getItem("lebahBest")||0,state="menu",camera=0,last=0,particles=[],powers=[],active={magnet:0,shield:0},musicTimer=0;
let profile=localStorage.getItem("lebahProfile")||"Pemain",totalHoney=+localStorage.getItem("lebahHoney")||0,selected=localStorage.getItem("lebahSkin")||"classic";
let settings=JSON.parse(localStorage.getItem("lebahSettings")||'{"music":true,"sfx":true,"vibrate":true,"contrast":false}');
const skins={classic:{name:"Klasik",emoji:"🐝",cost:0},gold:{name:"Emas",emoji:"🟡",cost:50},red:{name:"Merah",emoji:"🔴",cost:120},ghost:{name:"Hantu",emoji:"👻",cost:250},queen:{name:"Ratu",emoji:"👑",cost:500}};
let owned=JSON.parse(localStorage.getItem("lebahOwned")||'["classic"]');
const achievements=[["first","Langkah Pertama","Capai skor 15.",()=>score>=15],["honey","Pecinta Madu","Kumpulkan total 25 madu.",()=>totalHoney>=25],["level3","Penjelajah","Capai Level 3.",()=>level>=3],["score100","Lebah Hebat","Capai skor 100.",()=>score>=100],["score250","Raja Kebun","Capai skor 250.",()=>score>=250],["combo","Combo Master","Capai Combo x10.",()=>combo>=10]];
function save(){localStorage.setItem("lebahProfile",profile);localStorage.setItem("lebahHoney",totalHoney);localStorage.setItem("lebahSkin",selected);localStorage.setItem("lebahOwned",JSON.stringify(owned));localStorage.setItem("lebahSettings",JSON.stringify(settings))}
function resize(){let r=c.getBoundingClientRect();W=r.width;H=r.height;c.width=Math.floor(W*devicePixelRatio);c.height=Math.floor(H*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);COLS=Math.max(5,Math.floor(W/GRID))}addEventListener("resize",resize);resize();
const rnd=(a,b)=>Math.random()*(b-a)+a,pick=a=>a[Math.floor(Math.random()*a.length)];
function beep(freq=500,dur=.08,type="sine"){if(!settings.sfx)return;let A=new (window.AudioContext||window.webkitAudioContext)(),o=A.createOscillator(),g=A.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(A.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,A.currentTime+dur);o.stop(A.currentTime+dur)}
function vibrate(ms=25){if(settings.vibrate&&navigator.vibrate)navigator.vibrate(ms)}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),1000)}
class Bee{reset(){this.gx=Math.floor(COLS/2);this.gy=2;this.px=this.gx*GRID+5;this.py=H-this.gy*GRID+5;this.wave=0;this.jump=0}update(){this.px+=(this.gx*GRID+5-this.px)*.3;this.py+=(H-this.gy*GRID+5-this.py)*.3;this.wave+=.2}draw(){let X=this.px+20,Y=this.py+20+Math.sin(this.wave)*1.5;x.save();x.translate(X,Y);x.fillStyle="#0003";x.beginPath();x.ellipse(0,18,17,6,0,0,6.28);x.fill();x.font="38px sans-serif";x.textAlign="center";x.textBaseline="middle";x.fillText(skins[selected].emoji,0,0);if(active.shield>0){x.strokeStyle="#62cfff";x.lineWidth=3;x.beginPath();x.arc(0,0,28,0,6.28);x.stroke()}x.restore()}}
class Row{constructor(g,l){this.g=g;this.y=H-g*GRID;this.type=(g>2&&(g-2)%HIVE===0)?"hive":(Math.random()<.48?"safe":"flower");this.flowers=[];this.speed=rnd(1,1.8)*(1+(l-1)*.3)*(Math.random()<.5?-1:1);if(this.type==="flower")for(let i=0,n=2+Math.floor(Math.random()*3);i<n;i++)this.flowers.push({x:rnd(-30,W+30),r:rnd(18,23),rot:rnd(0,6.28),col:pick(["#ff5364","#9b59b6","#3498db","#f368e0"])})}update(dt){if(this.type==="flower")for(const f of this.flowers){f.x+=this.speed*dt;f.rot+=.01*dt;if(f.x>W+45)f.x=-45;if(f.x<-45)f.x=W+45}}draw(){let y=this.y+camera;if(y<-50||y>H+50)return;if(this.type==="safe"){ctx.fillStyle="#4ca82f";ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#77c957";for(let i=10;i<W;i+=45){ctx.beginPath();ctx.arc(i,y+25+(this.g%2)*5,2,0,6.28);ctx.fill()}}else if(this.type==="hive"){let g=ctx.createLinearGradient(0,y,0,y+GRID);g.addColorStop(0,"#f8c943");g.addColorStop(1,"#d78312");ctx.fillStyle=g;ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#fff9";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText("🍯 SARANG CHECKPOINT 🍯",W/2,y+30)}else{ctx.fillStyle="#61b838";ctx.fillRect(0,y,W,GRID);for(const f of this.flowers){ctx.save();ctx.translate(f.x,y+25);ctx.rotate(f.rot);ctx.fillStyle=f.col;for(let i=0;i<6;i++){ctx.rotate(1.047);ctx.beginPath();ctx.ellipse(f.r*.55,0,f.r*.5,f.r*.28,0,0,6.28);ctx.fill()}ctx.fillStyle="#ffe66d";ctx.beginPath();ctx.arc(0,0,7,0,6.28);ctx.fill();ctx.restore()}}}}
function spawnItem(){if(Math.random()<.006) powers.push({gx:Math.floor(Math.random()*COLS),gy:bee.gy+Math.floor(rnd(3,9)),type:Math.random()<.55?"honey":Math.random()<.5?"magnet":"shield",bob:Math.random()*6.28})}
function drawItems(){for(const p of powers){let y=H-p.gy*GRID+camera;if(y<-50||y>H+50)continue;let e=p.type==="honey"?"🍯":p.type==="magnet"?"🧲":"🛡️";ctx.font="26px sans-serif";ctx.textAlign="center";ctx.fillText(e,p.gx*GRID+25,y+26)}}
function collectItems(){let px=bee.gx,gy=bee.gy;for(let i=powers.length-1;i>=0;i--){let p=powers[i],near=Math.abs(p.gx-px)<=.2&&p.gy===gy;if(active.magnet>0&&p.type==="honey"&&Math.abs(p.gy-gy)<=4&&Math.abs(p.gx-px)<=3)near=true;if(near){powers.splice(i,1);if(p.type==="honey"){totalHoney++;runHoney++;combo++;score+=1+Math.min(combo,10);toast("🍯 +1 Madu  🔥 x"+combo);beep(760,.08,"triangle");particlesBurst(bee.px+20,bee.py+20,"#ffd34e",10)}else{active[p.type]=8;toast(p.type==="magnet"?"🧲 MAGNET AKTIF!":"🛡️ SHIELD AKTIF!");beep(500,.18,"square");particlesBurst(bee.px+20,bee.py+20,"#8ee7ff",16)}save();vibrate(20)}}}
function particlesBurst(px,py,kind,n=12){for(let i=0;i<n;i++)particles.push({x:px,y:py,vx:rnd(-3,3),vy:rnd(-3,3),life:1,size:rnd(2,6),kind})}
function drawParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.06*dt;p.life-=.035*dt;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.kind;ctx.fillRect(p.x,p.y,p.size,p.size);if(p.life<=0)particles.splice(i,1)}ctx.globalAlpha=1}
function newGame(){resize();rows=[];powers=[];particles=[];score=0;level=1;runHoney=0;combo=0;camera=0;active={magnet:0,shield:0};bee=new Bee;bee.reset();for(let i=0;i<24;i++){let r=new Row(i,1);if(i<=2){r.type="safe";r.flowers=[]}rows.push(r)}state="playing";hideScreens();$("pause").style.display="block";hud();beep(620,.12)}
function hideScreens(){document.querySelectorAll(".screen").forEach(e=>e.classList.add("hidden"))}
function hud(){$("level").textContent=level;$("score").textContent=score;$("honey").textContent=totalHoney;$("combo").textContent="x"+combo;let q=[];if(active.magnet>0)q.push("🧲 "+active.magnet.toFixed(1)+"s");if(active.shield>0)q.push("🛡️ "+active.shield.toFixed(1)+"s");$("powerHud").innerHTML=q.map(v=>`<div class="power">${v}</div>`).join("")}
function move(d){if(state==="menu"){newGame();return}if(state==="gameover"){newGame();return}if(state!=="playing")return;
 let oldY=bee.gy;if(d==="up")bee.gy++;else if(d==="down"&&bee.gy>2)bee.gy--;else if(d==="left"&&bee.gx>0)bee.gx--;else if(d==="right"&&bee.gx<COLS-1)bee.gx++;
 if(d==="up"&&bee.gy!==oldY){let dist=bee.gy-2;if(dist>score)score=dist;let nl=Math.floor(dist/HIVE)+1;if(nl>level){level=nl;score+=5;honeyBonus();toast("🏠 CHECKPOINT! +5 SKOR");beep(880,.2,"triangle");particlesBurst(bee.px+20,bee.py+20,"#fff06a",22)}}
 if(d!=="up"&&bee.gy===oldY)combo=0;checkAchievements();hud();beep(d==="up"?680:420,.045)}
function honeyBonus(){totalHoney+=3;runHoney+=3;save()}
function collision(){let r=rows.find(z=>z.g===bee.gy);if(!r||r.type!=="flower")return false;let px=bee.px+20,py=bee.py+20;for(const f of r.flowers)if(Math.hypot(px-f.x,py-(r.y+25))<f.r+13){if(active.shield>0){active.shield=0;toast("🛡️ SHIELD MELINDUNGI!");particlesBurst(px,py,"#7ee7ff",25);beep(250,.18,"sawtooth");vibrate(50);return false}let near=Math.hypot(px-f.x,py-(r.y+25))<f.r+28;if(near){score+=5;toast("😱 NEAR MISS! +5");particlesBurst(px,py,"#fff",10);beep(1000,.08,"triangle");combo++}else return true}return false}
function gameOver(){state="gameover";if(score>best){best=score;localStorage.setItem("lebahBest",best)}checkAchievements();save();$("finalScore").textContent=score;$("finalLevel").textContent=level;$("finalHoney").textContent=runHoney;$("finalBest").textContent=best;$("resultName").textContent=profile;$("newRecord").classList.toggle("hidden",score<best);$("gameover").classList.remove("hidden");$("pause").style.display="none";beep(130,.35,"sawtooth");vibrate(120)}
function checkAchievements(){let done=JSON.parse(localStorage.getItem("lebahAchievements")||"[]");for(const a of achievements)if(!done.includes(a[0])&&a[3]()){done.push(a[0]);localStorage.setItem("lebahAchievements",JSON.stringify(done));toast("🏆 "+a[1]+" terbuka!");beep(980,.18,"triangle")}}
function renderSkins(){$("shopHoney").textContent=totalHoney;$("skins").innerHTML="";for(const [id,s] of Object.entries(skins)){let own=owned.includes(id),d=document.createElement("div");d.className="skin "+(selected===id?"selected ":"")+(own?"":"locked");d.innerHTML=`<div class="emoji">${s.emoji}</div><b>${s.name}</b><br><small>${own?(selected===id?"DIPAKAI":"DIMILIKI"):"🍯 "+s.cost}</small>`;let b=document.createElement("button");b.className=own?"secondary":"primary";b.textContent=own?(selected===id?"AKTIF":"PILIH"):"BELI";b.onclick=()=>{if(own){selected=id;save();renderSkins()}else if(totalHoney>=s.cost){totalHoney-=s.cost;owned.push(id);selected=id;save();renderSkins();toast("🐝 Skin dibeli!");beep(900,.12)}else toast("🍯 Madu belum cukup!")};d.appendChild(b);$("skins").appendChild(d)}} 
function renderAchievements(){let done=JSON.parse(localStorage.getItem("lebahAchievements")||"[]");$("achievements").innerHTML=achievements.map(a=>`<div class="achievement ${done.includes(a[0])?"done":""}"><strong>${done.includes(a[0])?"✅":"🔒"} ${a[1]}</strong><small>${a[2]}</small></div>`).join("")}
const tut=["🐝 <b>GERAK</b><br>Swipe atau tekan tombol/Arrow untuk memindahkan lebah satu grid.","🌸 <b>HINDARI BUNGA</b><br>Bunga bergerak horizontal. Tabrakan tanpa shield membuat game over.","🍯 <b>KUMPULKAN MADU</b><br>Madu menjadi mata uang untuk membeli skin.","🧲 <b>POWER-UP MAGNET</b><br>Magnet menarik madu di sekitar lebah selama beberapa detik.","🛡️ <b>POWER-UP SHIELD</b><br>Shield menyelamatkanmu dari satu tabrakan.","🔥 <b>COMBO & NEAR MISS</b><br>Ambil madu beruntun untuk combo. Hindari bunga sangat dekat untuk bonus Near Miss.","🏠 <b>SARANG</b><br>Setiap 15 langkah kamu naik level dan mendapat bonus madu. Semakin tinggi level, semakin cepat bunga."];let ti=0;
function showTutorial(){ti=0;$("tutorialContent").innerHTML=tut[0];$("nextTutorial").textContent="LANJUT";$("start").classList.add("hidden");$("tutorialScreen").classList.remove("hidden")}
$("nextTutorial").onclick=()=>{ti++;if(ti>=tut.length){hideScreens();$("start").classList.remove("hidden");return}$("tutorialContent").innerHTML=tut[ti];$("nextTutorial").textContent=ti===tut.length-1?"SELESAI":"LANJUT"};
$("play").onclick=newGame;$("again").onclick=newGame;$("restartP").onclick=newGame;
$("resume").onclick=()=>{state="playing";$("pauseScreen").classList.add("hidden")};$("pause").onclick=()=>{if(state==="playing"){state="paused";$("pauseScreen").classList.remove("hidden")}};
$("menuP").onclick=()=>{$("home").click()};$("home").onclick=()=>{state="menu";hideScreens();$("start").classList.remove("hidden");$("pause").style.display="none"};
$("editName").onclick=()=>{$("nameInput").value=profile;hideScreens();$("nameScreen").classList.remove("hidden")};$("saveName").onclick=()=>{profile=$("nameInput").value.trim()||"Pemain";save();$("profileName").textContent=profile;hideScreens();$("start").classList.remove("hidden")};
$("tutorialMenu").onclick=showTutorial;$("shopMenu").onclick=()=>{renderSkins();hideScreens();$("shopScreen").classList.remove("hidden")};$("achMenu").onclick=()=>{renderAchievements();hideScreens();$("achScreen").classList.remove("hidden")};$("creditsMenu").onclick=()=>{hideScreens();$("creditsScreen").classList.remove("hidden")};
$("settingsMenu").onclick=()=>{hideScreens();$("settingsScreen").classList.remove("hidden")};
$("musicToggle").checked=settings.music;$("sfxToggle").checked=settings.sfx;$("vibrateToggle").checked=settings.vibrate;$("contrastToggle").checked=settings.contrast;
$("musicToggle").onchange=e=>{settings.music=e.target.checked;save()};$("sfxToggle").onchange=e=>{settings.sfx=e.target.checked;save()};$("vibrateToggle").onchange=e=>{settings.vibrate=e.target.checked;save()};$("contrastToggle").onchange=e=>{settings.contrast=e.target.checked;document.body.classList.toggle("contrast",settings.contrast);save()};
document.querySelectorAll(".back").forEach(b=>b.onclick=()=>{hideScreens();$("start").classList.remove("hidden")});
document.querySelectorAll("#controls button").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();move(b.dataset.dir)}));
let sx=0,sy=0;c.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY});c.addEventListener("pointerup",e=>{let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?dx>0?"right":"left":dy>0?"down":"up")});
addEventListener("keydown",e=>{let k=e.key.toLowerCase(),m={arrowup:"up",w:"up",arrowdown:"down",s:"down",arrowleft:"left",a:"left",arrowright:"right",d:"right"};if(m[k]){e.preventDefault();move(m[k])}if(k==="p")$("pause").click()});
$("profileName").textContent=profile;document.body.classList.toggle("contrast",settings.contrast);bee=new Bee;bee.reset();$("pause").style.display="none";hud();
function loop(t){let dt=Math.min(2,(t-last||16)/16);last=t;ctx.clearRect(0,0,W,H);
 if(state==="playing"){let top=rows[rows.length-1]?.g||0;if(bee.gy>top-10)for(let i=1;i<=12;i++)rows.push(new Row(top+i,level));if(rows.length>55)rows=rows.filter(r=>r.g>bee.gy-18);let target=bee.gy*GRID-H+250;camera+=(target-camera)*.08;active.magnet=Math.max(0,active.magnet-dt/60);active.shield=Math.max(0,active.shield-dt/60);spawnItem();collectItems()}
 for(const r of rows){r.update(dt);r.draw()}drawItems();if(bee){bee.update();ctx.save();ctx.translate(0,camera);bee.draw();ctx.restore()}drawParticles(dt);
 if(state==="playing"&&collision())gameOver();hud();requestAnimationFrame(loop)}
requestAnimationFrame(loop);