import {GRID,HIVE,skins,achievements} from "./data.js";
import * as S from "./storage.js";import {beep,vibrate} from "./audio.js";import {ParticleSystem} from "./particles.js";import {$,hideScreens,toast,renderProfile,renderShop,renderAchievements,hud,showTutorial} from "./ui.js";

const canvas=$("canvas"),ctx=canvas.getContext("2d");let W,H,COLS,rows=[],powers=[],bee,particles=new ParticleSystem(),state="menu",score=0,level=1,runHoney=0,combo=0,camera=0,last=0,active={magnet:0,shield:0},tutorialNext;
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;canvas.width=Math.floor(W*devicePixelRatio);canvas.height=Math.floor(H*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);COLS=Math.max(5,Math.floor(W/GRID))}
addEventListener("resize",resize);resize();const rnd=(a,b)=>Math.random()*(b-a)+a,pick=a=>a[Math.floor(Math.random()*a.length)];
class Bee{reset(){this.gx=Math.floor(COLS/2);this.gy=2;this.px=this.gx*GRID+5;this.py=H-this.gy*GRID+5;this.wave=0}update(dt=1){const f=Math.min(1,.3*dt);this.px+=(this.gx*GRID+5-this.px)*f;this.py+=(H-this.gy*GRID+5-this.py)*f;this.wave+=.2*dt}draw(){const X=this.px+20,Y=this.py+20+Math.sin(this.wave)*1.5;ctx.save();ctx.translate(X,Y);ctx.fillStyle="#0003";ctx.beginPath();ctx.ellipse(0,18,17,6,0,0,6.28);ctx.fill();ctx.font="38px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(skins[S.selected()].emoji,0,0);if(active.shield>0){ctx.strokeStyle="#62cfff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,28,0,6.28);ctx.stroke()}ctx.restore()}}
class Row{constructor(g,l){this.g=g;this.y=H-g*GRID;this.type=(g>2&&(g-2)%HIVE===0)?"hive":(Math.random()<.48?"safe":"flower");this.flowers=[];this.speed=rnd(1,1.8)*(1+(l-1)*.3)*(Math.random()<.5?-1:1);if(this.type==="flower")for(let i=0,n=2+Math.floor(Math.random()*3);i<n;i++)this.flowers.push({x:rnd(-30,W+30),r:rnd(18,23),rot:rnd(0,6.28),col:pick(["#ff5364","#9b59b6","#3498db","#f368e0"])})}update(dt){if(this.type==="flower")for(const f of this.flowers){f.x+=this.speed*dt;f.rot+=.01*dt;if(f.x>W+45)f.x=-45;if(f.x<-45)f.x=W+45}}draw(){const y=this.y+camera;if(y<-50||y>H+50)return;if(this.type==="safe"){ctx.fillStyle="#4ca82f";ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#77c957";for(let i=10;i<W;i+=45){ctx.beginPath();ctx.arc(i,y+25+(this.g%2)*5,2,0,6.28);ctx.fill()}}else if(this.type==="hive"){const g=ctx.createLinearGradient(0,y,0,y+GRID);g.addColorStop(0,"#f8c943");g.addColorStop(1,"#d78312");ctx.fillStyle=g;ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#fff9";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText("🍯 SARANG CHECKPOINT 🍯",W/2,y+30)}else{ctx.fillStyle="#61b838";ctx.fillRect(0,y,W,GRID);for(const f of this.flowers){ctx.save();ctx.translate(f.x,y+25);ctx.rotate(f.rot);ctx.fillStyle=f.col;for(let i=0;i<6;i++){ctx.rotate(1.047);ctx.beginPath();ctx.ellipse(f.r*.55,0,f.r*.5,f.r*.28,0,0,6.28);ctx.fill()}ctx.fillStyle="#ffe66d";ctx.beginPath();ctx.arc(0,0,7,0,6.28);ctx.fill();ctx.restore()}}}}
function save(){S.setHoney(S.totalHoney());S.setSelected(S.selected());S.setOwned(S.owned())}
function newGame(){resize();rows=[];powers=[];particles=new ParticleSystem();score=0;level=1;runHoney=0;combo=0;camera=0;active={magnet:0,shield:0};bee=new Bee;bee.reset();for(let i=0;i<24;i++){const r=new Row(i,1);if(i<=2){r.type="safe";r.flowers=[]}rows.push(r)}state="playing";hideScreens();$("pause").style.display="block";hud(level,score,S.totalHoney(),combo,active);beep(620,.12,"sine",S.settings().sfx)}
function move(d){if(state!=="playing")return;const oldY=bee.gy;if(d==="up")bee.gy++;else if(d==="down"&&bee.gy>2)bee.gy--;else if(d==="left"&&bee.gx>0)bee.gx--;else if(d==="right"&&bee.gx<COLS-1)bee.gx++;if(d==="up"&&bee.gy!==oldY){const dist=bee.gy-2;if(dist>score)score=dist;const nl=Math.floor(dist/HIVE)+1;if(nl>level){level=nl;score+=5;S.setHoney(S.totalHoney()+3);runHoney+=3;toast("🏠 CHECKPOINT! +5 SKOR +3 🍯");beep(880,.2,"triangle",S.settings().sfx);particles.burst(bee.px+20,bee.py+20,"#fff06a",22)}}if(d!=="up"&&bee.gy===oldY)combo=0;beep(d==="up"?680:420,.045,"sine",S.settings().sfx);checkAchievements();hud(level,score,S.totalHoney(),combo,active)}
function spawn(){if(Math.random()<.006)powers.push({gx:Math.floor(Math.random()*COLS),gy:bee.gy+Math.floor(rnd(3,9)),type:Math.random()<.55?"honey":Math.random()<.5?"magnet":"shield"})}
function collect(){for(let i=powers.length-1;i>=0;i--){const p=powers[i];let near=Math.abs(p.gx-bee.gx)<=.2&&p.gy===bee.gy;if(active.magnet>0&&p.type==="honey"&&Math.abs(p.gy-bee.gy)<=4&&Math.abs(p.gx-bee.gx)<=3)near=true;if(!near)continue;powers.splice(i,1);if(p.type==="honey"){S.setHoney(S.totalHoney()+1);runHoney++;combo++;score+=1+Math.min(combo,10);toast("🍯 +1 Madu 🔥 x"+combo);beep(760,.08,"triangle",S.settings().sfx);particles.burst(bee.px+20,bee.py+20,"#ffd34e",10)}else{active[p.type]=8;toast(p.type==="magnet"?"🧲 MAGNET AKTIF!":"🛡️ SHIELD AKTIF!");beep(500,.18,"square",S.settings().sfx);particles.burst(bee.px+20,bee.py+20,"#8ee7ff",16)}vibrate(20,S.settings().vibrate);save()}}
function drawPowers(){for(const p of powers){const y=H-p.gy*GRID+camera;if(y>-50&&y<H+50){ctx.font="26px sans-serif";ctx.textAlign="center";ctx.fillText(p.type==="honey"?"🍯":p.type==="magnet"?"🧲":"🛡️",p.gx*GRID+25,y+26)}}}
function collision(){const r=rows.find(z=>z.g===bee.gy);if(!r||r.type!=="flower")return false;const px=bee.px+20,py=bee.py+20;for(const f of r.flowers){const d=Math.hypot(px-f.x,py-(r.y+25));if(d<f.r+13){if(active.shield>0){active.shield=0;toast("🛡️ SHIELD MELINDUNGI!");particles.burst(px,py,"#7ee7ff",25);return false}return true}if(d<f.r+28&&d>=f.r+13){score+=5;combo++;toast("😱 NEAR MISS! +5");particles.burst(px,py,"#fff",10);beep(1000,.08,"triangle",S.settings().sfx)}}return false}
function checkAchievements(){const done=S.achievementsDone();const snap={score,totalHoney:S.totalHoney(),level,combo};for(const a of achievements)if(!done.includes(a[0])&&a[3](snap)){done.push(a[0]);S.setAchievements(done);toast("🏆 "+a[1]+" terbuka!");beep(980,.18,"triangle",S.settings().sfx)}}
function over(){state="gameover";let b=S.best(),isNew=score>b;if(isNew){S.setBest(score);b=score}checkAchievements();$("finalScore").textContent=score;$("finalLevel").textContent=level;$("finalHoney").textContent=runHoney;$("finalBest").textContent=b;$("resultName").textContent=S.profile();$("newRecord").classList.toggle("hidden",!isNew);$("gameover").classList.remove("hidden");$("pause").style.display="none";beep(130,.35,"sawtooth",S.settings().sfx);vibrate(120,S.settings().vibrate)}
function draw(dt){ctx.clearRect(0,0,W,H);for(const r of rows){r.update(dt);r.draw()}drawPowers();if(bee){bee.update(dt);ctx.save();ctx.translate(0,camera);bee.draw();ctx.restore()}particles.draw(ctx,dt);hud(level,score,S.totalHoney(),combo,active)}
function loop(t){const dt=Math.min(2,(t-last||16)/16);last=t;if(state==="playing"){const top=rows[rows.length-1]?.g||0;if(bee.gy>top-10)for(let i=1;i<=12;i++)rows.push(new Row(top+i,level));if(rows.length>55)rows=rows.filter(r=>r.g>bee.gy-18);camera+=(bee.gy*GRID-H+250-camera)*Math.min(1,.08*dt);active.magnet=Math.max(0,active.magnet-dt/60);active.shield=Math.max(0,active.shield-dt/60);spawn();collect();if(collision())over()}draw(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);

$("play").onclick=newGame;$("again").onclick=newGame;$("pause").onclick=()=>{if(state==="playing"){state="paused";$("pauseScreen").classList.remove("hidden")}};$("resume").onclick=()=>{state="playing";$("pauseScreen").classList.add("hidden")};$("restartP").onclick=newGame;$("menuP").onclick=$("home").onclick=()=>{state="menu";hideScreens();$("start").classList.remove("hidden");$("pause").style.display="none"};
$("editName").onclick=()=>{$("nameInput").value=S.profile();hideScreens();$("nameScreen").classList.remove("hidden")};$("saveName").onclick=()=>{S.saveProfile($("nameInput").value.trim()||"Pemain");renderProfile();hideScreens();$("start").classList.remove("hidden")};
$("tutorialMenu").onclick=()=>{hideScreens();$("tutorialScreen").classList.remove("hidden");showTutorial(fn=>tutorialNext=fn)};$("nextTutorial").onclick=()=>tutorialNext&&tutorialNext();
function refreshShop(){renderShop((id,s)=>{const own=S.owned();if(own.includes(id)){S.setSelected(id);refreshShop()}else if(S.totalHoney()>=s.cost){S.setHoney(S.totalHoney()-s.cost);own.push(id);S.setOwned(own);S.setSelected(id);refreshShop();toast("🐝 Skin dibeli!")}else toast("🍯 Madu belum cukup!")})}
$("shopMenu").onclick=()=>{refreshShop();hideScreens();$("shopScreen").classList.remove("hidden")};
$("achMenu").onclick=()=>{renderAchievements();hideScreens();$("achScreen").classList.remove("hidden")};$("settingsMenu").onclick=()=>{const x=S.settings();$("musicToggle").checked=x.music;$("sfxToggle").checked=x.sfx;$("vibrateToggle").checked=x.vibrate;$("contrastToggle").checked=x.contrast;hideScreens();$("settingsScreen").classList.remove("hidden")};$("creditsMenu").onclick=()=>{hideScreens();$("creditsScreen").classList.remove("hidden")};
$("musicToggle").onchange=e=>{const x=S.settings();x.music=e.target.checked;S.setSettings(x)};$("sfxToggle").onchange=e=>{const x=S.settings();x.sfx=e.target.checked;S.setSettings(x)};$("vibrateToggle").onchange=e=>{const x=S.settings();x.vibrate=e.target.checked;S.setSettings(x)};$("contrastToggle").onchange=e=>{const x=S.settings();x.contrast=e.target.checked;document.body.classList.toggle("contrast",x.contrast);S.setSettings(x)};
document.querySelectorAll(".back").forEach(b=>b.onclick=()=>{hideScreens();$("start").classList.remove("hidden")});document.querySelectorAll("#controls button").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();move(b.dataset.dir)}));
let sx=0,sy=0;canvas.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY});canvas.addEventListener("pointerup",e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?dx>0?"right":"left":dy>0?"down":"up")});
addEventListener("keydown",e=>{const m={arrowup:"up",w:"up",arrowdown:"down",s:"down",arrowleft:"left",a:"left",arrowright:"right",d:"right"};if(m[e.key.toLowerCase()]){e.preventDefault();move(m[e.key.toLowerCase()])}if(e.key.toLowerCase()==="p")$("pause").click()});
renderProfile();document.body.classList.toggle("contrast",S.settings().contrast);$("pause").style.display="none";hud(1,0,S.totalHoney(),0,active);