// ABOUTME: Core game loop — grid movement, spawning, collisions, scoring, and screen transitions.
// ABOUTME: Wires together canvas rendering, storage, audio, particles, and UI screens.
import {GRID,CHECKPOINT,skins,achievements} from "./data.js";
import * as S from "./storage.js";import {beep,vibrate,startMusic,stopMusic} from "./audio.js";import {ParticleSystem} from "./particles.js";import {$,hideScreens,toast,renderProfile,renderShop,renderAchievements,renderLeaderboard,hud,showTutorial,hydrateIcons} from "./ui.js";

if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));

const canvas=$("canvas"),ctx=canvas.getContext("2d");const catImg=new Image();catImg.src="cat-sprite.png";let W,H,COLS,rows=[],powers=[],cat,particles=new ParticleSystem(),state="menu",score=0,level=1,runFish=0,combo=0,powerUses=0,camera=0,last=0,active={magnet:0,shield:0,boost:0,double:0},tutorialNext,countdownTimer=null,shakeTime=0,flashAlpha=0;
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;canvas.width=Math.floor(W*devicePixelRatio);canvas.height=Math.floor(H*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);COLS=Math.max(5,Math.floor(W/GRID))}
addEventListener("resize",resize);addEventListener("orientationchange",()=>{setTimeout(resize,50);setTimeout(resize,300)});if(screen.orientation)screen.orientation.addEventListener("change",()=>setTimeout(resize,50));resize();const rnd=(a,b)=>Math.random()*(b-a)+a,pick=a=>a[Math.floor(Math.random()*a.length)];
class Cat{reset(){this.gx=Math.floor(COLS/2);this.gy=2;this.px=this.gx*GRID+5;this.py=H-this.gy*GRID+5;this.wave=0}update(dt=1){const f=Math.min(1,.3*dt);this.px+=(this.gx*GRID+5-this.px)*f;this.py+=(H-this.gy*GRID+5-this.py)*f;this.wave+=.2*dt}draw(){const X=this.px+20,Y=this.py+20+Math.sin(this.wave)*1.5,s=skins[S.selected()];ctx.save();ctx.translate(X,Y);ctx.fillStyle="#0003";ctx.beginPath();ctx.ellipse(0,18,17,6,0,0,6.28);ctx.fill();ctx.globalAlpha=s.alpha??1;if(catImg.complete&&catImg.naturalWidth){const iw=catImg.naturalWidth,ih=catImg.naturalHeight,dw=46,dh=dw*ih/iw,top=18-dh;ctx.drawImage(catImg,-dw/2,top,dw,dh);if(s.tint){ctx.globalCompositeOperation="source-atop";ctx.fillStyle=s.tint;ctx.fillRect(-dw/2,top,dw,dh);ctx.globalCompositeOperation="source-over"}if(s.crown){const cy=top+7;ctx.fillStyle="#ffd34e";ctx.strokeStyle="#7a4b00";ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(-9,cy);ctx.lineTo(-4.5,cy-9);ctx.lineTo(0,cy);ctx.lineTo(4.5,cy-9);ctx.lineTo(9,cy);ctx.closePath();ctx.fill();ctx.stroke()}}ctx.globalAlpha=1;if(active.shield>0){ctx.strokeStyle="#62cfff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-6,27,0,6.28);ctx.stroke()}if(active.boost>0){ctx.strokeStyle="#ff9d3f";ctx.lineWidth=2;ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(-14,20);ctx.lineTo(-14,30);ctx.moveTo(14,20);ctx.lineTo(14,30);ctx.stroke();ctx.globalAlpha=1}ctx.restore()}}
class Row{constructor(g,l){this.g=g;this.y=H-g*GRID;this.type=(g>2&&(g-2)%CHECKPOINT===0)?"home":(Math.random()<.48?"safe":"bee");this.bees=[];this.speed=rnd(1,1.8)*(1+(l-1)*.3)*(Math.random()<.5?-1:1);if(this.type==="bee")for(let i=0,n=2+Math.floor(Math.random()*3);i<n;i++)this.bees.push({x:rnd(-30,W+30),r:rnd(14,18),rot:rnd(0,6.28)})}update(dt){if(this.type==="bee")for(const b of this.bees){b.x+=this.speed*dt;b.rot+=.15*dt;if(b.x>W+45)b.x=-45;if(b.x<-45)b.x=W+45}}draw(){const y=this.y+camera;if(y<-50||y>H+50)return;if(this.type==="safe"){ctx.fillStyle="#4ca82f";ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#77c957";for(let i=10;i<W;i+=45){ctx.beginPath();ctx.arc(i,y+25+(this.g%2)*5,2,0,6.28);ctx.fill()}}else if(this.type==="home"){const g=ctx.createLinearGradient(0,y,0,y+GRID);g.addColorStop(0,"#f8c943");g.addColorStop(1,"#d78312");ctx.fillStyle=g;ctx.fillRect(0,y,W,GRID);ctx.fillStyle="#fff9";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText("RUMAH CHECKPOINT",W/2,y+30)}else{ctx.fillStyle="#61b838";ctx.fillRect(0,y,W,GRID);for(const b of this.bees){ctx.save();ctx.translate(b.x,y+25);const wingY=Math.sin(b.rot*4)*2;ctx.fillStyle="#fff9";ctx.beginPath();ctx.ellipse(-b.r*.4,wingY,b.r*.4,b.r*.26,-.4,0,6.28);ctx.fill();ctx.beginPath();ctx.ellipse(b.r*.4,wingY,b.r*.4,b.r*.26,.4,0,6.28);ctx.fill();ctx.fillStyle="#f6c343";ctx.beginPath();ctx.ellipse(0,0,b.r*.6,b.r*.4,0,0,6.28);ctx.fill();ctx.strokeStyle="#2b2118";ctx.lineWidth=2.2;ctx.lineCap="round";for(const dx of[-b.r*.25,0,b.r*.25]){ctx.beginPath();ctx.moveTo(dx,-b.r*.3);ctx.lineTo(dx,b.r*.3);ctx.stroke()}ctx.restore()}}}}
const clouds=Array.from({length:9},(_,i)=>({x:(i*113)%520+rnd(-20,20),yOff:i*140,rx:rnd(30,48),ry:rnd(14,20)}));
function drawBackground(){const span=1260,par=camera*.35;for(const c of clouds){let y=((c.yOff-par)%span+span)%span-140;ctx.fillStyle="#ffffff12";ctx.beginPath();ctx.ellipse(c.x%W,y,c.rx,c.ry,0,0,6.28);ctx.fill()}}
function save(){S.setFish(S.totalFish());S.setSelected(S.selected());S.setOwned(S.owned())}
function newGame(){resize();rows=[];powers=[];particles=new ParticleSystem();score=0;level=1;runFish=0;combo=0;powerUses=0;camera=0;active={magnet:0,shield:0,boost:0,double:0};shakeTime=0;flashAlpha=0;cat=new Cat;cat.reset();for(let i=0;i<24;i++){const r=new Row(i,1);if(i<=2){r.type="safe";r.bees=[]}rows.push(r)}hideScreens();$("pause").style.display="none";hud(level,score,S.totalFish(),combo,active);if(S.settings().music)startMusic();startCountdown()}
function startCountdown(){state="countdown";let n=3;const el=$("countdownOverlay");el.classList.remove("hidden");el.textContent=n;beep(500,.1,"sine",S.settings().sfx);clearInterval(countdownTimer);countdownTimer=setInterval(()=>{n--;if(n>0){el.textContent=n;beep(500,.1,"sine",S.settings().sfx)}else{el.textContent="MULAI!";beep(880,.2,"triangle",S.settings().sfx);clearInterval(countdownTimer);setTimeout(()=>{el.classList.add("hidden");state="playing";$("pause").style.display="block"},450)}},650)}
function move(d){if(state!=="playing")return;const oldY=cat.gy,upStep=active.boost>0?2:1;if(d==="up")cat.gy+=upStep;else if(d==="down"&&cat.gy>2)cat.gy--;else if(d==="left"&&cat.gx>0)cat.gx--;else if(d==="right"&&cat.gx<COLS-1)cat.gx++;if(d==="up"&&cat.gy!==oldY){const dist=cat.gy-2;if(dist>score)score=dist;const nl=Math.floor(dist/CHECKPOINT)+1;if(nl>level){level=nl;score+=5;S.setFish(S.totalFish()+3);runFish+=3;toast("Checkpoint! +5 skor, +3 ikan");beep(880,.2,"triangle",S.settings().sfx);particles.burst(cat.px+20,cat.py+20,"#fff06a",22)}}if(d!=="up"&&cat.gy===oldY)combo=0;beep(d==="up"?680:420,.045,"sine",S.settings().sfx);checkAchievements();hud(level,score,S.totalFish(),combo,active)}
function spawn(){if(Math.random()<.007)powers.push({gx:Math.floor(Math.random()*COLS),gy:cat.gy+Math.floor(rnd(3,9)),type:Math.random()<.45?"fish":pick(["magnet","shield","boost","double"])})}
function collect(){for(let i=powers.length-1;i>=0;i--){const p=powers[i];let near=Math.abs(p.gx-cat.gx)<=.2&&p.gy===cat.gy;if(active.magnet>0&&p.type==="fish"&&Math.abs(p.gy-cat.gy)<=4&&Math.abs(p.gx-cat.gx)<=3)near=true;if(!near)continue;powers.splice(i,1);if(p.type==="fish"){const mult=active.double>0?2:1;S.setFish(S.totalFish()+1);runFish++;combo++;score+=(1+Math.min(combo,10))*mult;toast("+1 Ikan, Combo x"+combo);beep(760,.08,"triangle",S.settings().sfx);particles.burst(cat.px+20,cat.py+20,"#8ee7ff",10)}else{active[p.type]=8;powerUses++;const label={magnet:"Magnet aktif!",shield:"Shield aktif!",boost:"Lari Cepat aktif!",double:"Skor Ganda aktif!"}[p.type];toast(label);beep(500,.18,"square",S.settings().sfx);particles.burst(cat.px+20,cat.py+20,"#8ee7ff",16)}vibrate(20,S.settings().vibrate);save()}}
function drawPowers(){for(const p of powers){const y=H-p.gy*GRID+camera;if(y<-50||y>H+50)continue;const cx=p.gx*GRID+25,cy=y+25;ctx.save();ctx.translate(cx,cy);if(p.type==="fish"){ctx.fillStyle="#8ee7ff";ctx.strokeStyle="#2b93b8";ctx.lineWidth=1.4;ctx.beginPath();ctx.ellipse(-2,0,8,5,0,0,6.28);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(6,0);ctx.lineTo(12,-5);ctx.lineTo(12,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#0b3d4d";ctx.beginPath();ctx.arc(-7,-1,1.3,0,6.28);ctx.fill()}else if(p.type==="magnet"){ctx.strokeStyle="#e0473f";ctx.lineWidth=6;ctx.lineCap="round";ctx.beginPath();ctx.arc(0,2,8,3.4,6.02);ctx.stroke();ctx.strokeStyle="#c7ccd6";ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-8,2);ctx.lineTo(-8,-8);ctx.moveTo(8,2);ctx.lineTo(8,-8);ctx.stroke()}else if(p.type==="boost"){ctx.strokeStyle="#ff9d3f";ctx.lineWidth=4;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();ctx.moveTo(-7,4);ctx.lineTo(0,-4);ctx.lineTo(7,4);ctx.stroke();ctx.beginPath();ctx.moveTo(-7,11);ctx.lineTo(0,3);ctx.lineTo(7,11);ctx.stroke()}else if(p.type==="double"){ctx.fillStyle="#ffd34e";ctx.strokeStyle="#b8860b";ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(0,0,11,0,6.28);ctx.fill();ctx.stroke();ctx.fillStyle="#3a2600";ctx.font="bold 13px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("x2",0,1)}else{ctx.fillStyle="#8ee7ff";ctx.strokeStyle="#2b93b8";ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(0,-11);ctx.quadraticCurveTo(10,-7,10,-1);ctx.quadraticCurveTo(10,7,0,12);ctx.quadraticCurveTo(-10,7,-10,-1);ctx.quadraticCurveTo(-10,-7,0,-11);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}}
function collision(){const r=rows.find(z=>z.g===cat.gy);if(!r||r.type!=="bee")return false;const px=cat.px+20,py=cat.py+20,mult=active.double>0?2:1;for(const b of r.bees){const d=Math.hypot(px-b.x,py-(r.y+25));if(d<b.r+10){if(active.shield>0){active.shield=0;toast("Shield melindungi!");particles.burst(px,py,"#7ee7ff",25);return false}shakeTime=16;flashAlpha=1;return true}if(d<b.r+22&&d>=b.r+10){score+=5*mult;combo++;toast("Nyaris kena! +"+5*mult);particles.burst(px,py,"#fff",10);beep(1000,.08,"triangle",S.settings().sfx)}}return false}
function checkAchievements(){const done=S.achievementsDone();const snap={score,totalFish:S.totalFish(),level,combo,powerUses};for(const a of achievements)if(!done.includes(a[0])&&a[3](snap)){done.push(a[0]);S.setAchievements(done);toast(a[1]+" terbuka!");beep(980,.18,"triangle",S.settings().sfx)}}
function over(){state="gameover";let b=S.best(),isNew=score>b;if(isNew){S.setBest(score);b=score}S.addToLeaderboard({name:S.profile(),score,level});checkAchievements();$("finalScore").textContent=score;$("finalLevel").textContent=level;$("finalFish").textContent=runFish;$("finalBest").textContent=b;$("resultName").textContent=S.profile();$("newRecord").classList.toggle("hidden",!isNew);$("gameover").classList.remove("hidden");$("pause").style.display="none";beep(130,.35,"sawtooth",S.settings().sfx);vibrate(120,S.settings().vibrate)}
function draw(dt){ctx.clearRect(0,0,W,H);ctx.save();if(shakeTime>0){shakeTime=Math.max(0,shakeTime-dt);const m=Math.min(8,shakeTime);ctx.translate((Math.random()*2-1)*m,(Math.random()*2-1)*m)}drawBackground();for(const r of rows){r.update(dt);r.draw()}drawPowers();if(cat){cat.update(dt);ctx.save();ctx.translate(0,camera);cat.draw();ctx.restore()}particles.draw(ctx,dt);ctx.restore();if(flashAlpha>0){flashAlpha=Math.max(0,flashAlpha-dt*.08);ctx.fillStyle=`rgba(255,40,40,${flashAlpha*.5})`;ctx.fillRect(0,0,W,H)}hud(level,score,S.totalFish(),combo,active)}
function loop(t){const dt=Math.min(2,(t-last||16)/16);last=t;if(state==="playing"){const top=rows[rows.length-1]?.g||0;if(cat.gy>top-10)for(let i=1;i<=12;i++)rows.push(new Row(top+i,level));if(rows.length>55)rows=rows.filter(r=>r.g>cat.gy-18);camera+=(cat.gy*GRID-H+250-camera)*Math.min(1,.08*dt);active.magnet=Math.max(0,active.magnet-dt/60);active.shield=Math.max(0,active.shield-dt/60);active.boost=Math.max(0,active.boost-dt/60);active.double=Math.max(0,active.double-dt/60);spawn();collect();if(collision())over()}draw(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);

$("play").onclick=newGame;$("again").onclick=newGame;$("pause").onclick=()=>{if(state==="playing"){state="paused";$("pauseScreen").classList.remove("hidden")}};$("resume").onclick=()=>{state="playing";$("pauseScreen").classList.add("hidden")};$("restartP").onclick=newGame;$("menuP").onclick=$("home").onclick=()=>{state="menu";hideScreens();$("start").classList.remove("hidden");$("pause").style.display="none"};
$("editName").onclick=()=>{$("nameInput").value=S.profile();hideScreens();$("nameScreen").classList.remove("hidden")};$("saveName").onclick=()=>{S.saveProfile($("nameInput").value.trim()||"Pemain");renderProfile();hideScreens();$("start").classList.remove("hidden")};
$("tutorialMenu").onclick=()=>{hideScreens();$("tutorialScreen").classList.remove("hidden");showTutorial(fn=>tutorialNext=fn)};$("nextTutorial").onclick=()=>tutorialNext&&tutorialNext();
function refreshShop(){renderShop((id,s)=>{const own=S.owned();if(own.includes(id)){S.setSelected(id);refreshShop()}else if(S.totalFish()>=s.cost){S.setFish(S.totalFish()-s.cost);own.push(id);S.setOwned(own);S.setSelected(id);refreshShop();toast("Skin dibeli!")}else toast("Ikan belum cukup!")})}
$("shopMenu").onclick=()=>{refreshShop();hideScreens();$("shopScreen").classList.remove("hidden")};
$("achMenu").onclick=()=>{renderAchievements();hideScreens();$("achScreen").classList.remove("hidden")};$("leaderboardMenu").onclick=()=>{renderLeaderboard();hideScreens();$("leaderboardScreen").classList.remove("hidden")};$("settingsMenu").onclick=()=>{const x=S.settings();$("musicToggle").checked=x.music;$("sfxToggle").checked=x.sfx;$("vibrateToggle").checked=x.vibrate;$("contrastToggle").checked=x.contrast;hideScreens();$("settingsScreen").classList.remove("hidden")};$("creditsMenu").onclick=()=>{hideScreens();$("creditsScreen").classList.remove("hidden")};
$("musicToggle").onchange=e=>{const x=S.settings();x.music=e.target.checked;S.setSettings(x);if(x.music)startMusic();else stopMusic()};$("sfxToggle").onchange=e=>{const x=S.settings();x.sfx=e.target.checked;S.setSettings(x)};$("vibrateToggle").onchange=e=>{const x=S.settings();x.vibrate=e.target.checked;S.setSettings(x)};$("contrastToggle").onchange=e=>{const x=S.settings();x.contrast=e.target.checked;document.body.classList.toggle("contrast",x.contrast);S.setSettings(x)};
document.querySelectorAll(".back").forEach(b=>b.onclick=()=>{hideScreens();$("start").classList.remove("hidden")});document.querySelectorAll("#controls button").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();move(b.dataset.dir)}));
let sx=0,sy=0;canvas.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY});canvas.addEventListener("pointerup",e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?dx>0?"right":"left":dy>0?"down":"up")});
addEventListener("keydown",e=>{const m={arrowup:"up",w:"up",arrowdown:"down",s:"down",arrowleft:"left",a:"left",arrowright:"right",d:"right"};if(m[e.key.toLowerCase()]){e.preventDefault();move(m[e.key.toLowerCase()])}if(e.key.toLowerCase()==="p")$("pause").click()});
renderProfile();hydrateIcons();document.body.classList.toggle("contrast",S.settings().contrast);$("pause").style.display="none";hud(1,0,S.totalFish(),0,active);
