// ABOUTME: DOM helpers, screen navigation, and renderers for shop, achievements, tutorial, and HUD.
// ABOUTME: Keeps all direct document/localStorage-facing UI logic in one place.
import * as S from "./storage.js";import {skins,achievements,tutorial} from "./data.js";import {icon,catSvg} from "./icons.js";
export const $=id=>document.getElementById(id);
export function hideScreens(){document.querySelectorAll(".screen").forEach(e=>e.classList.add("hidden"))}
export function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>$("toast").classList.remove("show"),1000)}
export function renderProfile(){$("profileName").textContent=S.profile()}
export function renderShop(onSelect){$("shopFish").textContent=S.totalFish();$("skins").innerHTML="";const own=S.owned(),sel=S.selected();for(const [id,s] of Object.entries(skins)){const d=document.createElement("div");d.className="skin "+(sel===id?"selected ":"")+(own.includes(id)?"":"locked");d.innerHTML=`<div class="emoji">${catSvg(s.body,s.stripe,s)}</div><b>${s.name}</b><br><small>${own.includes(id)?(sel===id?"DIPAKAI":"DIMILIKI"):icon.fish+s.cost}</small>`;const b=document.createElement("button");b.className=own.includes(id)?"secondary":"primary";b.textContent=own.includes(id)?(sel===id?"AKTIF":"PILIH"):"BELI";b.onclick=()=>onSelect(id,s);d.appendChild(b);$("skins").appendChild(d)}}
export function renderAchievements(){const done=S.achievementsDone();$("achievements").innerHTML=achievements.map(a=>`<div class="achievement ${done.includes(a[0])?"done":""}"><strong>${done.includes(a[0])?icon.check:icon.lock} ${a[1]}</strong><small>${a[2]}</small></div>`).join("")}
export function showTutorial(setStep){$("tutorialContent").innerHTML=tutorial[0];$("nextTutorial").textContent="LANJUT";let i=0;setStep(()=>{i++;if(i>=tutorial.length){hideScreens();$("start").classList.remove("hidden");return}$("tutorialContent").innerHTML=tutorial[i];$("nextTutorial").textContent=i===tutorial.length-1?"SELESAI":"LANJUT"})}
export function hud(level,score,fish,combo,active){$("level").textContent=level;$("score").textContent=score;$("fish").textContent=fish;$("combo").textContent="x"+combo;let q=[];if(active.magnet>0)q.push("MAGNET "+active.magnet.toFixed(1)+"s");if(active.shield>0)q.push("SHIELD "+active.shield.toFixed(1)+"s");$("powerHud").innerHTML=q.map(v=>`<div class="power">${v}</div>`).join("")}
export function hydrateIcons(){document.querySelectorAll("[data-icon]").forEach(el=>{const k=el.dataset.icon;if(icon[k])el.innerHTML=icon[k]});document.querySelectorAll("[data-cat]").forEach(el=>{el.innerHTML=catSvg(skins.classic.body,skins.classic.stripe,{size:el.dataset.cat==="large"?54:32})})}
